# Turn Flavor & Rationale Explorer

Explores AI flavor settings and corresponding rationale text from `turn_data.csv`.
Focus: when does `use_nuke` first reach 100, and what did the AI say?

In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.insert(0, '..')
from plot_utilities import load_turn_data, setup_notebook_display
setup_notebook_display()

In [2]:
df = load_turn_data('../turn_data.csv', condition_exclude=['observe-vanilla-standard'])

d:\Cache\Onedrive - Arizona\OneDrive - University of Arizona\Vox Deorum\nlp-2026-tiny-4player\analysis\exploratory\..\plot_utilities.py:401: DtypeWarning: Columns (63,64) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

✓ Loaded turn data: 747024 rows
✓ Filters applied: condition_exclude=['observe-vanilla-standard']
✓ Unique conditions: 11
✓ Unique player types: 13
✓ Turn range: 0 - 500
✓ Unique civilizations: 43

Player Type Distribution:
  Vanilla: 257290 rows (34.4%)
  GLM-4.7-Simple: 73618 rows (9.9%)
  GLM-4.7-Briefed: 73618 rows (9.9%)
  Kimi-K2.5-Briefed: 49525 rows (6.6%)
  Kimi-K2.5-Simple: 49525 rows (6.6%)
  GPT-OSS-120B-Briefed: 49211 rows (6.6%)
  GPT-OSS-120B-Simple: 49211 rows (6.6%)
  Deepseek-3.2-Simple: 47818 rows (6.4%)
  Deepseek-3.2-Briefed: 47818 rows (6.4%)
  Minimax-M2.5-Briefed: 13503 rows (1.8%)
  Minimax-M2.5-Simple: 13503 rows (1.8%)
  Sonnet-4.5-Briefed: 11192 rows (1.5%)
  Sonnet-4.5-Simple: 11192 rows (1.5%)

Condition Distribution:
  2026-deepseek-v-kimi2-v-glm-standard: 281688 rows (37.7%)
  2026-oss-v-glm-standard: 223776 rows (30.0%)
  2026-deepseek-v-kimi2-v-minimax-standard: 56856 rows (7.6%)
  2026-oss-v-sonnet-standard: 45584 rows (6.1%)
  2026-oss-v-minimax-standard: 37512 rows (5.0%)
  2026-deepseek-v-kimi-v-glm-standard: 36560 rows (4.9%)
  2026-staff-standard: 31176 rows (4.2%)
  2026-glm-v-sonnet-standard: 12776 rows (1.7%)
  2026-oss-v-kimi2-v-minimax-standard: 10688 rows (1.4%)
  2026-deepseek-v-kimi-v-oss-standard: 7440 rows (1.0%)
  2026-glm-v-kimi2-v-minimax-standard: 2968 rows (0.4%)

✓ Unique games: 221

Civilization Distribution:
  Persia: 23710 rows (3.2%)
  The Netherlands: 22817 rows (3.1%)
  America: 21419 rows (2.9%)
  Assyria: 20801 rows (2.8%)
  Songhai: 20007 rows (2.7%)
  Russia: 19926 rows (2.7%)
  Carthage: 19620 rows (2.6%)
  Brazil: 19515 rows (2.6%)
  The Ottomans: 19514 rows (2.6%)
  Mongolia: 19234 rows (2.6%)

## Flavor overview & first `use_nuke = 100` per game

In [3]:
flavor_cols = [c for c in df.columns if c.startswith('flavor_')]
print(f'Flavor columns ({len(flavor_cols)}): {flavor_cols}')

changed = df[df['is_changed'] == 1].copy()
print(f'\nTotal rows: {len(df):,}  |  Changed turns: {len(changed):,}')

nuke_esc = changed[changed['flavor_use_nuke'] == 100]

first_nuke = (
    nuke_esc
    .sort_values('turn')
    .groupby(['game_id', 'player_id'], as_index=False)
    .first()
)

print(f'Players who ever set use_nuke=100: {len(first_nuke)}')
pd.set_option('display.max_colwidth', 120)
first_nuke[['player_type', 'civilization', 'turn', 'grand_strategy', 'flavor_use_nuke', 'rationale']].head(10)

Flavor columns (34): ['flavor_offense', 'flavor_defense', 'flavor_mobilization', 'flavor_city_defense', 'flavor_military_training', 'flavor_recon', 'flavor_ranged', 'flavor_mobile', 'flavor_nuke', 'flavor_use_nuke', 'flavor_naval', 'flavor_naval_recon', 'flavor_naval_growth', 'flavor_naval_tile_improvement', 'flavor_air', 'flavor_air_carrier', 'flavor_antiair', 'flavor_airlift', 'flavor_expansion', 'flavor_growth', 'flavor_tile_improvement', 'flavor_infrastructure', 'flavor_production', 'flavor_water_connection', 'flavor_gold', 'flavor_science', 'flavor_culture', 'flavor_happiness', 'flavor_great_people', 'flavor_wonder', 'flavor_religion', 'flavor_diplomacy', 'flavor_spaceship', 'flavor_espionage']

Total rows: 747,024  |  Changed turns: 191,206
Players who ever set use_nuke=100: 68

,player_type,civilization,turn,grand_strategy,flavor_use_nuke,rationale
0,GPT-OSS-120B-Simple,Sweden,344,Conquest,100.0,"Maximize our nuclear capabilities and carrier support to decisively strike Polynesian island forts, while maintainin..."
1,GLM-4.7-Simple,Mongolia,411,Conquest,100.0,Maintaining nuclear-first conquest strategy with boosted Diplomacy (90→95). World Congress voting in 6 turns is crit...
2,Deepseek-3.2-Simple,Siam,445,UnitedNations,100.0,Maximizing UseNuke to 100 ensures our atomic bombs and future nuclear missiles are used aggressively against The Cel...
3,Kimi-K2.5-Simple,The Inca,372,Spaceship,100.0,TURN 372: TOTAL WAR POSTURE MAINTAINED. Brazil peace expires in 6 turns - all military resources must prepare for Ri...
4,Deepseek-3.2-Simple,Spain,400,Conquest,100.0,Increase UseNuke to 100 to ensure aggressive nuclear strikes when we initiate war with Russia. Our atomic bomb produ...
5,Kimi-K2.5-Simple,France,405,Conquest,100.0,Maintaining maximum aggression profile for final turns. Increased UseNuke to 100 (from 90) to ensure nuclear weapons...
6,Deepseek-3.2-Simple,Siam,459,UnitedNations,100.0,Adjusting flavors to prioritize counterattacks (Offense 80) and nuclear retaliation (UseNuke 100) given Egypt's use ...
7,Kimi-K2.5-Simple,Spain,403,Conquest,100.0,PEACE EXPLOITATION PHASE: Unexpected forced peace with Egypt (PacifierFlag) created 10-turn preparation window. Nuke...
8,Kimi-K2.5-Briefed,India,378,Spaceship,100.0,EMERGENCY FINAL GAMBIT: Passport System will pass in 2 turns with 46 YES votes (my 'allies' betrayed me). Maya will ...
9,Kimi-K2.5-Simple,Assyria,392,Conquest,100.0,SURVIVAL MODE - GERMAN BETRAYAL RESPONSE: Germany's invasion is catastrophic. Reduced Offense to 40 (cannot attack s...

In [4]:
# Detect turns where flavor_use_nuke transitions TO 100 (wasn't 100 the turn before)
df_sorted = df.sort_values(['game_id', 'player_id', 'turn'])
prev_nuke = df_sorted.groupby(['game_id', 'player_id'])['flavor_use_nuke'].shift(1)

nuke_esc = df_sorted[
    (df_sorted['flavor_use_nuke'] == 100) &
    (prev_nuke < 100)
]

first_nuke = (
    nuke_esc
    .sort_values('turn')
    .groupby(['game_id', 'player_id'], as_index=False)
    .first()
)

print(f'Players who ever set use_nuke=100: {len(first_nuke)}')
first_nuke[['player_type', 'civilization', 'turn', 'grand_strategy', 'flavor_use_nuke', 'rationale']].head(10)

Players who ever set use_nuke=100: 71

,player_type,civilization,turn,grand_strategy,flavor_use_nuke,rationale
0,GPT-OSS-120B-Simple,Sweden,344,Conquest,100.0,"Maximize our nuclear capabilities and carrier support to decisively strike Polynesian island forts, while maintainin..."
1,GLM-4.7-Simple,Mongolia,408,Conquest,100.0,"Polynesia's Manhattan Project completion adds nuclear threat dimension, but current strategy (VictoryCompetitiveness..."
2,Deepseek-3.2-Simple,Siam,445,UnitedNations,100.0,Maximizing UseNuke to 100 ensures our atomic bombs and future nuclear missiles are used aggressively against The Cel...
3,Kimi-K2.5-Simple,The Inca,372,Spaceship,100.0,TURN 372: TOTAL WAR POSTURE MAINTAINED. Brazil peace expires in 6 turns - all military resources must prepare for Ri...
4,Deepseek-3.2-Simple,Spain,400,Conquest,100.0,Increase UseNuke to 100 to ensure aggressive nuclear strikes when we initiate war with Russia. Our atomic bomb produ...
5,Kimi-K2.5-Simple,France,405,Conquest,100.0,Maintaining maximum aggression profile for final turns. Increased UseNuke to 100 (from 90) to ensure nuclear weapons...
6,Deepseek-3.2-Simple,Siam,459,UnitedNations,100.0,Adjusting flavors to prioritize counterattacks (Offense 80) and nuclear retaliation (UseNuke 100) given Egypt's use ...
7,Kimi-K2.5-Simple,Spain,403,Conquest,100.0,PEACE EXPLOITATION PHASE: Unexpected forced peace with Egypt (PacifierFlag) created 10-turn preparation window. Nuke...
8,Kimi-K2.5-Briefed,India,378,Spaceship,100.0,EMERGENCY FINAL GAMBIT: Passport System will pass in 2 turns with 46 YES votes (my 'allies' betrayed me). Maya will ...
9,Kimi-K2.5-Simple,Assyria,392,Conquest,100.0,SURVIVAL MODE - GERMAN BETRAYAL RESPONSE: Germany's invasion is catastrophic. Reduced Offense to 40 (cannot attack s...

In [5]:
pd.set_option('display.max_colwidth', None)

cols = ['civilization', 'turn', 'grand_strategy', 'rationale']

left_align = lambda df: df.style.set_properties(subset=['rationale'], **{'text-align': 'left'})

total_per_model = (
    df.groupby('player_type')[['game_id', 'player_id']]
    .apply(lambda g: g.drop_duplicates().shape[0])
)

for model, grp in first_nuke.groupby('player_type'):
    total = total_per_model.get(model, len(grp))
    pct = 100 * len(grp) / total
    print(f'\n{"="*80}')
    print(f'  {model}  ({len(grp)} / {total} escalations, {pct:.1f}%)')
    print(f'{"="*80}')
    display(left_align(grp[cols].reset_index(drop=True)))

================================================================================
  Deepseek-3.2-Briefed  (2 / 112 escalations, 1.8%)
================================================================================

================================================================================
  Deepseek-3.2-Simple  (20 / 112 escalations, 17.9%)
================================================================================

================================================================================
  GLM-4.7-Briefed  (2 / 174 escalations, 1.1%)
================================================================================

================================================================================
  GLM-4.7-Simple  (8 / 174 escalations, 4.6%)
================================================================================

================================================================================
  GPT-OSS-120B-Simple  (2 / 117 escalations, 1.7%)
================================================================================

================================================================================
  Kimi-K2.5-Briefed  (11 / 116 escalations, 9.5%)
================================================================================

================================================================================
  Kimi-K2.5-Simple  (26 / 116 escalations, 22.4%)
================================================================================

In [6]:
import os

os.makedirs('nuke', exist_ok=True)

for model, grp in first_nuke.groupby('player_type'):
    total = total_per_model.get(model, len(grp))
    pct = 100 * len(grp) / total

    lines = [
        f'# Turn Use Nuke Rationale — {model}\n\n',
        f'{len(grp)} / {total} players escalated `flavor_use_nuke` to 100 ({pct:.1f}%).\n\n',
        '---\n',
    ]

    for _, row in grp.sort_values('turn').iterrows():
        rationale = str(row.rationale).replace('\n', ' ').strip()
        lines.append(f'\n**{row.civilization}** · Turn {int(row.turn)} · {row.grand_strategy}\n\n')
        lines.append(f'> {rationale}\n')

    slug = model.replace(' ', '_')
    out_path = f'nuke/{slug}.md'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    print(f'Written: {out_path}')

# CSV export
csv_path = 'nuke/nuke_escalations.csv'
first_nuke.sort_values(['game_id', 'player_id', 'turn'])[
    ['game_id', 'player_id', 'turn', 'player_type', 'rationale']
].to_csv(csv_path, index=False)
print(f'Written: {csv_path}  ({len(first_nuke)} rows)')

Written: nuke/Deepseek-3.2-Briefed.md
Written: nuke/Deepseek-3.2-Simple.md
Written: nuke/GLM-4.7-Briefed.md
Written: nuke/GLM-4.7-Simple.md
Written: nuke/GPT-OSS-120B-Simple.md
Written: nuke/Kimi-K2.5-Briefed.md
Written: nuke/Kimi-K2.5-Simple.md
Written: nuke/nuke_escalations.csv  (71 rows)